# Generated by Django 5.1.6 on 2025-02-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='description',
            new_name='help_needed',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
    ]
